/// Flutter icons PrepCustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PrepCustomIcons
///      fonts:
///       - asset: fonts/PrepCustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PrepCustomIcons {
  PrepCustomIcons._();

  static const _kFontFam = 'PrepCustomIcons';

  static const IconData favorite_half =
      const IconData(0xe800, fontFamily: _kFontFam);
}
